yay -Syu hyprland dunst kitty thunar rofi qt5-wayland qt6-wayland sddm ranger xdg-desktop-portal-hyprland xdg-desktop-portal
sed -i 's/^autogenerated = 1 # remove this line to remove the warning/autogenerated = 0 # remove this line to remove the warning/' ~/.config/hypr/hyprland.conf
sed -i 's/^    kb_layout = us/    kb_layout = hu/' ~/.config/hypr/hyprland.conf
echo "bind =, XF86AudioRaiseVolume, exec, pw-volume change +5%" >> ~/.config/hypr/hyprland.conf
echo "bind =, XF86AudioLowerVolume, exec, pw-volume change -5%" >> ~/.config/hypr/hyprland.conf
echo "bind =, XF86AudioMute, exec, pw-volume mute toggle" >> ~/.config/hypr/hyprland.conf
sudo systemctl enable sddm
sudo reboot